# if you want to try the docker as your development env:
# Prerequisite if you want to run TF or CLI:
#     export IBMCLOUD_API_KEY=<YOURS>   # pragma: allowlist secret
# Run:
#   docker-compose run jammy
version: "3.3"
services:
  jammy:
    privileged: true
    build:
      context: .
    image: ghcr.io/ibm-xaas/dev-env:nightly
    #platform: linux/amd64
    volumes:
      # For future ssh use in development
      - ~/.ssh:/home/ubuntu/.ssh:ro
      - .:/jammy
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.gitconfig:/home/ubuntu/.gitconfig:ro
    environment:
      IBMCLOUD_API_KEY: "$IBMCLOUD_API_KEY"
    working_dir: /jammy
